
#ifndef _JACKET_PROTOCOL_H_
#define _JACKET_PROTOCOL_H_

#define JKP_MAGIC 0x76543210

#define JKP_MASK_CONTROL 0x1
#define JKP_MASK_BRAKE 0x2
#define JKP_MASK_TURNSIG_L 0x4
#define JKP_MASK_TURNSIG_R 0x8
#define JKP_MASK_PROX_SL 0x10
#define JKP_MASK_PROX_SR 0x20
#define JKP_MASK_PROX_FL 0x40
#define JKP_MASK_PROX_FR 0x80
#define JKP_MASK_BUZZ_L 0x100
#define JKP_MASK_BUZZ_R 0x200
#define JKP_MASK_VIB_L 0x400
#define JKP_MASK_VIB_R 0x800
#define JKP_MASK_MAX 0x1000

#endif //_JACKET_PROTOCOL_H_
