
#ifndef _SPEED_PROTOCOL_H_
#define _SPEED_PROTOCOL_H_

#define SPEED_BAUD_RATE 115200
#define SPEED_BAUD_RATE_SPEED_T B115200

#define SPEED_REQ_SPEED '0'
#define SPEED_REQ_ACCEL '1'
#define SPEED_REQ_INIT_MAGIC 'x'

#define SPEED_ACCEL_0G 333
#define SPEED_ACCEL_1G 400
#define SPEED_ACCEL_RAW_TO_MM_PER_SEC_2 (((SPEED_ACCEL_1G - SPEED_ACCEL_0G) * MM_PER_M) / 9.81)
#define SPEED_ACCEL_MM_PER_SEC_2_TO_RAW (1.0 / SPEED_ACCEL_RAW_TO_MM_PER_SEC_2)

#endif //_SPEED_PROTOCOL_H_
